# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# Branch build whitelist
branches:
  only:
  - dev

# Add in development pkgs
addons:
  apt: 
    packages: 
      - libv8-dev