library(shiny)

#' Internal utility for defualt plot message generation
#'
#' \code{ppg_data_check_empty_plot} creates a plot with a user-facing message stating that no data has been loaded.
#'

ppg_data_check_empty_plot <- function(){
  df <- data.frame(x=c(-1,0,1), y=c(-1,0,1))
  p <- ggplot(aes(x=x, y=y), data=df) +
    annotate('text', x=0, y=0, label='No Processed Data Provided') +
    theme_bw()

  return(p)
}

#' Internal utility for plot generation
#'
#' \code{generate_ppg_data_check_plot} defines the properties of the plot called on the UI Processing Panel to check
#' that the PPG data loading process was successful. The utility and resulting plot allow a user to visually inspect
#' the imported signal based on settings defined on the UI Data Entry panel
#'
#' @param ppg_data is a \code{data.frame} that contains the processed PPG signal and a time variable.
#' @param ppg_col is of type \code{character} and is the column name in the \code{ppg_data} that contains the PPG signal
#' @param time_col is of type \code{character} and is the column name in the \code{ppg_data} that contains the time
#' variable
#'
#' @export
#'

generate_ppg_data_check_plot <- function(ppg_data = NULL, ppg_col='PPG', time_col='Time'){
  p <- ggplot(data=ppg_data)+
    geom_line(aes_string(x=time_col,
                         y=ppg_col)) +
    labs(x="Time (s)", y="PPG (volts)") +
    theme_bw()
  return(p)
}

#' Internal utility for gui plot generation
#'
#' \code{generate_base_gui_plot} defines the base plot that forms the basis for interactively editing IBIs
#'
#' @param ibi_data is a \code{data.frame} that contains the IBI series being activel edited by the user during the
#' session
#' @param ibi_col is of type \code{character} and is the column name in the \code{ibi_data} that contains the IBI series
#' @param time_col is of type \code{character} and is the column name in the \code{ppg_data} that contains the time
#' variable
#'
#'@export
#'

generate_base_gui_plot <- function(ibi_data=NULL, color_map=NULL, ibi_col="IBI", time_col='Time'){
  p <- ggplot(data=ibi_data,
              aes_string(x=Time, y=IBI)) +
    geom_point(aes(color=pnt_type)) +
    geom_line(color="black") +
    scale_color_manual(values=color_map)
    labs(x="Time (s)", y="IBI (s)")
  return(p)
}

#' Internal utility for modifying gui plot
#'
#' \code{add_task_v_lines} adds vertical lines that delineate the timing boundaries of tasks/conditions defined in the
#' timing file
#'
#' @param base_plot is a \code{ggplot2} object, typically generated by \code{generate_base_gui_plot}
#' @param timing_data is a \code{data.frame} that contains time stamps for the start and stop of different
#' tasks/conditions
#' @param time_col is of type \code{character} and is the column name in the \code{timing_data} that contains start/stop
#' time stamps
#' @param task_col is of type \code{character} and is the column name in the \code{timing_data} that contains
#' task/condition names
#'
#' @export
#'

add_task_v_lines <- function(base_plot=NULL, timing_data=NULL, time_col='Time', task_col="Task"){
  if(!is.null(timing_data) & !is.null(plot)){
    p <- base_plot +
      geom_vline(data=rv$timing_data,
                 aes_string(xintercept=time_col,
                            color=task_col),
                 show.legend = FALSE)
    return(p)
  }
  else{
    return(base_plot)
  }
}


#' Internal \code{ibiVizEdit} utility that adds PPG to plot
#'
#' @export

add_ppg_waveform <- function(base_plot=NULL, ppg_data=NULL, show_ppg=FALSE, time_col="Time", ppg_col="PPG"){
  if(show_ppg & !is.null(ppg_data)){
    p <- base_plot +
      geom_line(data=ppg_data,
                aes_string(x=time_col,
                           y=ppg_col,
                           color="pnt_type"),
                inherit.aes=FALSE,
                alpha=.75,
                color="grey")
    return(p)
  }
  else{
    return(base_plot)
  }
}

#' Internal \code{ibiVizEdit} utility that enables dynamic color selection based on selected points
#'
#' @export

highlight_ibis <- function(base_plot=NULL, selected_points=NULL, time_col="Time", ibi_col="IBI"){
  if(!is.null(selected_points)){
    p <- base_plot +
      geom_point(data=selected_points,
                 aes_string(x=time_col,
                            y=ibi_col),
                 inherit.aes=FALSE,
                 color="#8fff00")
    return(p)
  }
  else{
    return(base_plot)
  }
}
